[package]
name = "fast-dtw"
version = "0.1.0"
authors = ["Ross Tollefson <ross@past9systems.com>"]
edition = "2018"

[dependencies]
libm = "0.2.1"

[dev-dependencies]
rand = "0.7.3"
image = "0.23.11"

